packages:
  - 'packages/*'
allowBuilds:
  '@parcel/watcher': true
  unrs-resolver: true
  esbuild: false
  "@nestjs/core": false
  lmdb: true
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - '@spartan-ng/cli@1.6.3'
  - '@spartan-ng/brain@1.6.3'
